//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by stage.rc
//
#define IDC_REMOVE                      3
#define IDC_INHERIT_PARENT              3
#define IDR_SRVR_INPLACE                4
#define IDC_CLEAR_ALL                   4
#define IDR_SRVR_EMBEDDED               5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_STAGE_TOP                   103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_STAGE_LEFT                  104
#define IDC_LINK                        104
#define IDR_MAINFRAME                   128
#define IDR_STAGETYPE                   129
#define IDD_PREFS_RENDER                130
#define IDR_MAINFRAME1                  130
#define IDD_PREFS_GRID                  131
#define IDD_PART                        132
#define IDD_DEVICE_PART                 133
#define IDD_PREFS_LIGHTING              135
#define IDD_DEVICE_TREE                 136
#define IDD_CHOOSE_NAME                 137
#define IDD_EYE_MOTION                  138
#define IDD_CHOOSE_DEVICE               140
#define IDD_DEVICE_TRANSFORMATION       141
#define IDD_EYE                         142
#define IDD_DIALOG2                     143
#define IDD_PREFS_OUTPUT                144
#define IDD_PART_MOTION                 145
#define IDB_BITMAP_TEST                 146
#define IDD_LIGHT_PART                  146
#define IDB_PLAYBACK_BACKGROUND         146
#define IDB_REWIND                      147
#define IDB_CIRCLE_GREEN                148
#define IDB_CIRCLE_GREEN2               148
#define IDB_PAUSE                       149
#define IDB_WALK                        150
#define IDB_PAN                         151
#define IDB_PLAY                        152
#define IDB_CIRCLE_YELLOW               153
#define IDB_CIRCLE_RED                  154
#define IDB_CIRCLE_GRAY                 154
#define IDB_DEVICE_TRANSLATE            155
#define IDD_LIGHT_DLG                   156
#define IDD_INHERIT                     157
#define IDD_ANALYSIS                    158
#define IDB_SQUARE_GRAY                 159
#define IDB_SQUARE_PURPLE               160
#define IDD_ROBOT6_SETUP                161
#define IDB_SIM_REC                     161
#define IDD_TAG                         162
#define IDB_CIRCLE_GREEN1               162
#define IDB_CIRCLE_RED1                 163
#define IDD_ROBOT6_DIALOG               164
#define IDB_CIRCLE_YELLOW1              164
#define IDC_SELECT                      165
#define IDB_DEVICE_TRANSLATE1           165
#define IDC_UNLINK                      166
#define IDD_ROTARY_TABLE_DLG            166
#define IDB_PAN1                        166
#define IDD_GRIPPER_DLG                 167
#define IDB_PAUSE1                      167
#define IDD_EYE_VIEW_DLG                168
#define IDB_PLAY1                       168
#define IDD_TRACK                       169
#define IDB_REWIND1                     169
#define IDD_TRAIN_DLG                   170
#define IDB_SIM_REC1                    170
#define IDD_CONVEYOR_DLG                171
#define IDB_WALK1                       171
#define IDD_BAR_CODE_READER_DLG         172
#define IDB_IWALK2                      172
#define IDD_BARRETTHAND                 173
#define IDB_BUTTON_BACKGROUND           173
#define IDD_SCALE_DLG                   174
#define IDB_IWALK3                      174
#define IDD_SCRIPT_DLG                  175
#define IDB_BUTTON_BACKGROUND1          175
#define IDD_CAMERA_DLG                  176
#define IDB_TOP_BACKGROUND              176
#define IDB_IWALK                       177
#define IDD_ROBOT6_DIALOG_CARTESIAN     177
#define IDB_IPAN                        178
#define IDB_IDEVICE_TRANSLATE           179
#define IDB_IEYE                        180
#define IDB_ISCROLL                     181
#define IDB_IRECORD                     182
#define IDB_ISOCKET                     183
#define IDB_LEFT_BACKGROUND             184
#define IDB_CIRCLE_RED2                 185
#define IDB_CIRCLE_WHITE                186
#define IDB_CIRCLE_CONNECT_GREEN        187
#define IDB_EYE_BACKGROUND              188
#define IDB_IPLAY                       189
#define IDB_IPAUSE                      190
#define IDB_IREWIND                     191
#define IDB_BITMAP1                     192
#define IDB_BITMAP3                     195
#define IDB_PLAY24                      196
#define IDB_PAUSE24                     197
#define IDB_REWIND24                    198
#define IDB_WALK24                      203
#define IDB_SCRIPT24                    206
#define IDB_EYE24                       207
#define IDB_SOCKET24                    208
#define IDB_RECORD24                    209
#define IDB_PAN24                       210
#define IDB_DEVICE_TRANSLATE24          211
#define IDB_PAUSE24_HL                  212
#define IDB_PLAY24_HL                   213
#define IDB_REWIND24_HL                 214
#define IDD_SIZE_CUSTOM                 215
#define IDB_LOOP                        216
#define IDD_PREFS_UNITS                 216
#define IDB_LOOP_ON                     217
#define IDD_PREFS_NETWORK               217
#define IDB_CIRCLE_CONNECT              218
#define IDB_CIRCLE_CONNECT_GREEN1       219
#define IDC_MODE_WALK                   1003
#define IDC_QUICK_POLYGON               1003
#define IDC_MODE_PAN                    1004
#define IDC_QUICK_WIREFRAME             1004
#define IDC_QUICK_TEXTURE               1005
#define IDC_MODE_DEVICE_TRANSFORMATIONS 1005
#define IDC_RENDER_POLYGON              1006
#define IDC_MODE_EYE                    1006
#define IDC_RENDER_WIREFRAME            1007
#define IDC_MODE_DEVICE_TRANSLATE       1007
#define IDC_RENDER_TEXTURE              1008
#define IDC_MODE_RECORD_SIM             1008
#define IDC_RENDER_FULL_3D              1009
#define IDC_MODE_SOCKET                 1009
#define IDC_SHADOWS                     1010
#define IDC_MOTION_BLUR                 1011
#define IDC_MOTION_BLUR_ITERATIONS      1012
#define IDC_GRID_VISIBLE                1013
#define IDC_TIME_END_MINUTES            1013
#define IDC_GRID_LENGTH                 1014
#define IDC_TIME_END_SECONDS            1014
#define IDC_GRID_WIDTH                  1015
#define IDC_TIME_END_FRAMES             1015
#define IDC_GRID_SPACING                1016
#define IDC_FRAMES_PER_SECOND           1016
#define IDC_GRID_SLIDER_RED             1017
#define IDC_PORT                        1017
#define IDC_GRID_SLIDER_GREEN           1018
#define IDC_SHADOW_SENSITIVITY          1018
#define IDC_GRID_SLIDER_BLUE            1019
#define IDC_PART_NAME                   1019
#define IDC_REAL_TIME                   1019
#define IDC_GRID_RED                    1020
#define IDC_COMBO1                      1020
#define IDC_DEVICE_NAME9                1020
#define IDC_ANTIALIAS                   1020
#define IDC_GRID_GREEN                  1021
#define IDC_PART_RED                    1021
#define IDC_BOUNDING_BOX                1021
#define IDC_GRID_BLUE                   1022
#define IDC_PART_GREEN                  1022
#define IDC_AUTO_SOCKET_SERVER          1022
#define IDC_PART_BLUE                   1023
#define IDC_OUTPUT_BITMAP               1023
#define IDC_PART_SLIDER_BLUE            1024
#define IDC_SMOOTH_SHADING              1024
#define IDC_PART_ALPHA                  1025
#define IDC_PART_SLIDER_ALPHA           1026
#define IDC_PART_SLIDER_RED             1027
#define IDC_PART_SLIDER_GREEN           1028
#define IDC_PART_WIREFRAME              1029
#define IDC_SLIDER_ROTATE_X             1029
#define IDC_PARENT_NAME9                1029
#define IDC_PART_POLYLINE               1030
#define IDC_PART_SHININESS              1030
#define IDC_PART_POLYPOINT              1031
#define IDC_PART_SLIDER_SHININESS       1031
#define IDC_PART_POLYFILLED             1032
#define IDC_PART_PARENT_NAME            1032
#define IDC_PART_TEXTURE_MAP            1033
#define IDC_SLIDER_ROTATE_Y             1033
#define IDC_SMOOTH_SHADE_ANGLE          1033
#define IDC_PART_NAME2                  1034
#define IDC_SLIDER_ROTATE_Z             1034
#define IDC_PART_TEXTURE2               1035
#define IDC_TRANSLATE_X                 1038
#define IDC_TRANSLATE_Y                 1039
#define IDC_TRANSLATE_Z                 1040
#define IDC_TXYZ                        1041
#define IDC_PART_MATERIAL               1042
#define IDC_DEVICE_VISIBLE              1043
#define IDC_LIGHTING_RED                1044
#define IDC_ROTATE_X                    1044
#define IDC_LIGHTING_SLIDER_RED         1045
#define IDC_ROTATE_Y                    1045
#define IDC_LIGHTING_SLIDER_GREEN       1046
#define IDC_ROTATE_Z                    1046
#define IDC_LIGHTING_SLIDER_BLUE        1047
#define IDC_PART_RENDER_MODE            1047
#define IDC_LIGHTING_BLUE               1048
#define IDC_TEXTURE_BLENDING            1048
#define IDC_LIGHTING_GREEN              1049
#define IDC_SNAP_TO_LIST                1049
#define IDC_LIGHTING_ALPHA              1050
#define IDC_MASS                        1050
#define IDC_LIGHTING_SLIDER_ALPHA       1051
#define IDC_BAR_CODE                    1051
#define IDC_LOCAL_VIEWER                1052
#define IDC_ORIGIN_VISIBLE              1052
#define IDC_TWO_SIDE                    1053
#define IDC_DEVICE_TREE                 1053
#define IDC_ORIGIN_ALT_DISPLAYED        1053
#define IDC_LIGHTING_SUN_SLIDER_INTENSITY 1054
#define IDC_MINUTES                     1055
#define IDC_LIGHTING_SUN_INTENSITY      1055
#define IDC_SECONDS                     1056
#define IDC_FRAMES                      1057
#define IDC_TIME                        1058
#define IDC_REWIND                      1065
#define IDC_PAUSE                       1066
#define IDC_EYE_MOTION_LIST             1066
#define IDC_PLAY                        1067
#define IDC_IMMEDIATE_MODE              1068
#define IDC_SLIDER_SHADOW_SENSITIVITY   1073
#define IDC_PART_TEXTURE                1075
#define IDC_TEXTURE_NAME                1076
#define IDC_LIST_PARTS9                 1077
#define IDC_LIST_DEVICES9               1078
#define IDC_LIST_PARENTS9               1079
#define IDC_LIST_NAME                   1083
#define IDC_EDIT_NAME                   1084
#define IDC_XYZ                         1094
#define IDC_TRANSLATE_RESTORE           1095
#define IDC_ROTATE_RESTORE              1096
#define IDC_TRANSLATE                   1097
#define IDC_RED_RESTORE                 1097
#define IDC_ROTATE                      1098
#define IDC_GREEN_RESTORE               1098
#define IDC_TRANSLATE_INCREASE          1099
#define IDC_BLUE_RESTORE                1099
#define IDC_TRANSLATE_DECREASE          1100
#define IDC_ALPHA_RESTORE               1100
#define IDC_SLIDER_ROTATE               1101
#define IDC_SHININESS_RESTORE           1101
#define IDC_TEXTURE_ROTATE              1102
#define IDC_ORIGIN_ALT_CREATE           1103
#define IDC_BUTTON1                     1113
#define IDC_SLIDER1                     1114
#define IDC_J2_TYPE                     1114
#define IDC_EYE_RESTORE_FROM            1115
#define IDC_J3_TYPE                     1115
#define IDC_EYE_RESTORE_TO              1116
#define IDC_J4_TYPE                     1116
#define IDC_J5_TYPE                     1117
#define IDC_J6_TYPE                     1118
#define IDC_EYE_RESTORE_FOV             1123
#define IDC_EYE_SLIDER_FOV              1125
#define IDC_EYE_CLIPFRONT_RESTORE       1126
#define IDC_EYE_CLIPREAR_RESTORE        1127
#define IDC_EYE_CLIPFRONT               1128
#define IDC_EYE_CLIPREAR                1129
#define IDC_EYE_FROMY                   1130
#define IDC_EYE_FROMX                   1131
#define IDC_OUTPUT_320X240              1131
#define IDC_EYE_TOX                     1132
#define IDC_OUTPUT_640X480              1132
#define IDC_PART_MOTION_LIST            1132
#define IDC_EYE_TOY                     1133
#define IDC_OUTPUT_720X540              1133
#define IDC_PART_REMOVE                 1133
#define IDC_EYE_TOZ                     1134
#define IDC_OUTPUT_RGB                  1134
#define IDC_PART_CLEAR_ALL              1134
#define IDC_EYE_FROMZ                   1135
#define IDC_OUTPUT_TIFF                 1135
#define IDC_UNITS_MILLIMETERS           1135
#define IDC_EYE_FOV                     1136
#define IDC_OUTPUT_FULL_SCREEN          1136
#define IDC_UNITS_INCHES                1136
#define IDC_DEVICE_PARENT_NAME          1136
#define IDC_OUTPUT_VARIABLE             1137
#define IDC_UNITS_FEET                  1137
#define IDC_UNITS_METERS                1138
#define IDC_TRANSLATE_INCREASE_X        1138
#define IDC_OUTPUT_ASPECT_RATIO         1139
#define IDC_TRANSLATE_DECREASE_X        1139
#define IDC_OUTPUT_ASPECT_4_3           1140
#define IDC_TRANSLATE_INCREASE_Y        1140
#define IDC_OUTPUT_ASPECT_4_4           1141
#define IDC_TRANSLATE_DECREASE_Y        1141
#define IDC_OUTPUT_ASPECT_4_5           1142
#define IDC_TRANSLATE_INCREASE_Z        1142
#define IDC_TRANSLATE_DECREASE_Z        1143
#define IDC_ROTATE_INCREASE_X           1144
#define IDC_ROTATE_INCREASE_Y           1145
#define IDC_ROTATE_INCREASE_Z           1146
#define IDC_DEVICE_VISIBLE9             1147
#define IDC_ROTATE_DECREASE_X           1147
#define IDC_LIGHT_ENABLED9              1148
#define IDC_ROTATE_DECREASE_Y           1148
#define IDC_LIGHT_POINT_SOURCE9         1149
#define IDC_ROTATE_DECREASE_Z           1149
#define IDC_PART_NAME9                  1150
#define IDC_TRANSLATE_X9                1151
#define IDC_TRANSLATE_Y9                1152
#define IDC_TRANSLATE_Z9                1153
#define IDC_ROTATE_X9                   1154
#define IDC_ROTATE_Y9                   1155
#define IDC_ROTATE_Z9                   1156
#define IDC_TXYZ9                       1157
#define IDC_LIGHT_INTENSITY9            1158
#define IDC_LIGHT_SLIDER_INTENSITY9     1159
#define IDC_LIST_ATTENUATION9           1160
#define IDC_LIGHT_ATTENUATION9          1161
#define IDC_LIGHT_SLIDER_ATTENUATION9   1162
#define IDC_LIGHT_SPOTLIGHT_ANGLE9      1163
#define IDC_LIGHT_SLIDER_SPOTLIGHT_ANGLE9 1164
#define IDC_PART_RED9                   1165
#define IDC_PART_GREEN9                 1166
#define IDC_PART_BLUE9                  1167
#define IDC_PART_ALPHA9                 1168
#define IDC_PART_SLIDER_RED9            1169
#define IDC_PART_SLIDER_GREEN9          1170
#define IDC_PART_SLIDER_BLUE9           1171
#define IDC_PART_SLIDER_ALPHA9          1172
#define IDC_PART_MATERIAL9              1173
#define IDC_PART_RENDER_MODE9           1174
#define IDC_PART_SHININESS9             1175
#define IDC_TEXTURE_NAME9               1176
#define IDC_PART_SLIDER_SHININESS9      1177
#define IDC_PART_TEXTURE9               1178
#define IDC_LIGHT_INTENSITY             1181
#define IDC_LIGHT_SLIDER_INTENSITY      1182
#define IDC_RESTORE_LIGHT_INTENSITY     1183
#define IDC_LIGHT_ATTENUATION           1184
#define IDC_LIGHT_SLIDER_ATTENUATION    1185
#define IDC_RESTORE_LIGHT_ATTENUATION   1186
#define IDC_LIGHT_ATTENUATION_LIST      1187
#define IDC_LIGHT_SPOTLIGHT_ANGLE       1188
#define IDC_LIGHT_SLIDER_SPOTLIGHT_ANGLE 1189
#define IDC_RESTORE_LIGHT_SPOTLIGHT_ANGLE 1190
#define IDC_LIGHT_ENABLED               1191
#define IDC_LIGHT_POINT_SOURCE          1192
#define IDC_PART_PARENT_INHERIT         1192
#define IDC_TEXTURE_NEW                 1193
#define IDC_TEXTURE_DELETE              1194
#define IDC_POLYGON_CENTER              1194
#define IDC_EDGE_CENTER                 1195
#define IDC_SNAP_TO                     1195
#define IDC_VERTEX                      1196
#define IDC_PART_ORIGIN                 1196
#define IDC_COORDINATE                  1197
#define IDC_PART                        1198
#define IDC_DEVICE                      1199
#define IDC_WORLD                       1200
#define IDC_POLYGON                     1201
#define IDC_EDGE                        1202
#define IDC_PART_FIRST                  1203
#define IDC_PART_SECOND                 1204
#define IDC_DEVICE_FIRST                1205
#define IDC_DEVICE_SECOND               1206
#define IDC_WORLD_FIRST                 1207
#define IDC_WORLD_SECOND                1208
#define IDC_COORDINATE_FIRST            1209
#define IDC_COORDINATE_SECOND           1210
#define IDC_VERTEX_FIRST                1211
#define IDC_VERTEX_SECOND               1212
#define IDC_EDGE_FIRST                  1213
#define IDC_EDGE_SECOND                 1214
#define IDC_POLYGON_FIRST               1215
#define IDC_POLYGON_SECOND              1216
#define IDC_EDGE_CENTERED_FIRST         1217
#define IDC_EDGE_CENTERED_SECOND        1218
#define IDC_POLYGON_CENTERED_FIRST      1219
#define IDC_POLYGON_CENTERED_SECOND     1220
#define IDC_OFFSET_X                    1221
#define IDC_OFFSET_Y                    1222
#define IDC_OFFSET_Z                    1223
#define IDC_RESET_X                     1224
#define IDC_RESET_Y                     1225
#define IDC_RESET_Z                     1226
#define IDC_DISTANCE                    1227
#define IDC_FIRST                       1228
#define IDC_SECOND                      1229
#define IDC_J1_MIN                      1230
#define IDC_J1_MAX                      1231
#define IDC_J1_MAX_ACCEL                1232
#define IDC_J1_MAX_SPEED                1233
#define IDC_J1_MIN_ACCEL_TIME           1234
#define IDC_J2_MIN                      1235
#define IDC_J2_MAX                      1236
#define IDC_J2_MAX_ACCEL                1237
#define IDC_J2_MAX_SPEED                1238
#define IDC_J2_MIN_ACCEL_TIME           1239
#define IDC_J3_MIN                      1240
#define IDC_J3_MAX                      1241
#define IDC_J3_MAX_ACCEL                1242
#define IDC_J3_MAX_SPEED                1243
#define IDC_J3_MIN_ACCEL_TIME           1244
#define IDC_J4_MIN                      1245
#define IDC_J4_MAX                      1246
#define IDC_J4_MAX_ACCEL                1247
#define IDC_J4_MAX_SPEED                1248
#define IDC_J4_MIN_ACCEL_TIME           1249
#define IDC_J5_MIN                      1250
#define IDC_J5_MAX                      1251
#define IDC_J5_MAX_ACCEL                1252
#define IDC_J5_MAX_SPEED                1253
#define IDC_J5_MIN_ACCEL_TIME           1254
#define IDC_J6_MIN                      1255
#define IDC_J6_MAX                      1256
#define IDC_J6_MAX_ACCEL                1257
#define IDC_J6_MAX_SPEED                1258
#define IDC_J6_MIN_ACCEL_TIME           1259
#define IDC_J1_TYPE                     1260
#define IDC_PATH_DEVICE                 1261
#define IDC_MAX_SCREW_SPEED             1261
#define IDC_PATH_VISIBLE                1262
#define IDC_MAX_TOOL_SPEED              1262
#define IDC_PATH_PART                   1263
#define IDC_MAX_SCREW_ACCEL             1263
#define IDC_TAG_TRANSLATE               1264
#define IDC_MAX_TOOL_ACCEL              1264
#define IDC_TAG_ROTATE                  1265
#define IDC_TCF_X                       1265
#define IDC_TAG_TRANSLATE_X             1266
#define IDC_TCF_RX                      1266
#define IDC_TAG_ROTATE_X                1267
#define IDC_TCF_Y                       1267
#define IDC_TAG_90_X                    1268
#define IDC_TCF_RY                      1268
#define IDC_TAG_TRANSLATE_Y             1269
#define IDC_TCF_Z                       1269
#define IDC_TAG_TRANSLATE_Z             1270
#define IDC_TCF_RZ                      1270
#define IDC_TAG_ROTATE_Y                1271
#define IDC_TAG_ROTATE_Z                1272
#define IDC_TAG_90_Y                    1273
#define IDC_TAG_90_Z                    1274
#define IDC_PATH_RED                    1276
#define IDC_PATH_SLIDER_RED             1277
#define IDC_PATH_RED_RESTORE            1278
#define IDC_PATH_GREEN                  1279
#define IDC_PATH_SLIDER_GREEN           1280
#define IDC_PATH_GREEN_RESTORE          1281
#define IDC_PATH_BLUE                   1282
#define IDC_PATH_SLIDER_BLUE            1283
#define IDC_PATH_BLUE_RESTORE           1284
#define IDC_TAG_SNAP                    1286
#define IDC_JOINT1                      1287
#define IDC_JOINT2                      1288
#define IDC_JOINT3                      1289
#define IDC_JOINT4                      1290
#define IDC_JOINT5                      1291
#define IDC_JOINT6                      1292
#define IDC_INCREASE_JOINT1             1293
#define IDC_INCREASE_JOINT2             1294
#define IDC_INCREASE_JOINT3             1295
#define IDC_INCREASE_JOINT4             1296
#define IDC_INCREASE_JOINT5             1297
#define IDC_INCREASE_JOINT6             1298
#define IDC_DECREASE_JOINT1             1299
#define IDC_DECREASE_JOINT2             1300
#define IDC_DECREASE_JOINT3             1301
#define IDC_DECREASE_JOINT4             1302
#define IDC_DECREASE_JOINT5             1303
#define IDC_DECREASE_JOINT6             1304
#define IDC_SPEED                       1305
#define IDC_INTERPOLATION_JOINT         1306
#define IDC_INTERPOLATION_LINEAR        1307
#define IDC_MIN_ACCEL_TIME              1308
#define IDC_HOME                        1309
#define IDC_X                           1310
#define IDC_Y                           1311
#define IDC_Z                           1312
#define IDC_RX                          1313
#define IDC_RY                          1314
#define IDC_RZ                          1315
#define IDC_INCREASE_X                  1316
#define IDC_INCREASE_Y                  1317
#define IDC_INCREASE_Z                  1318
#define IDC_INCREASE_RX                 1319
#define IDC_INCREASE_RY                 1320
#define IDC_INCREASE_RZ                 1321
#define IDC_DECREASE_X                  1322
#define IDC_DECREASE_Y                  1323
#define IDC_DECREASE_Z                  1324
#define IDC_DECREASE_RX                 1325
#define IDC_DECREASE_RY                 1326
#define IDC_DECREASE_RZ                 1327
#define IDC_SETUP                       1328
#define IDC_LEFTY                       1329
#define IDC_RIGHTY                      1330
#define IDC_ELBOW_UP                    1331
#define IDC_ELBOW_DOWN                  1332
#define IDC_WRIST_FLIPPED               1333
#define IDC_ESTOP                       1334
#define IDC_ROTARY_TABLE_VELOCITY       1335
#define IDC_ROTARY_TABLE_ACCEL          1336
#define IDC_ROTARY_TABLE_END_POSITION   1337
#define IDC_ROTARY_TABLE_CURRENT_POSITION 1339
#define IDC_ROTARY_TABLE_GO             1340
#define IDC_ROTARY_TABLE_HOME           1341
#define IDC_GRIPPER_DISPLACEMENT_OPEN   1341
#define IDC_ROTARY_TABLE_TIME_OF_MOVE   1342
#define IDC_GRIPPER_OPEN                1342
#define IDC_ROTARY_TABLE_DIRECTION      1343
#define IDC_GRIPPER_CLOSE               1343
#define IDC_GRIPPER_DISPLACEMENT_CLOSE  1344
#define IDC_BARRETTHAND_SPREAD          1345
#define IDC_GRIPPER_TYPE_TRANSLATING    1346
#define IDC_BARRETTHAND_SPREAD_OPEN     1346
#define IDC_GRIPPER_TYPE_ROTATING       1347
#define IDC_BARRETTHAND_SPREAD_CLOSE    1347
#define IDC_EYE_VIEW_SET                1348
#define IDC_BARRETTHAND_VELOCITY        1348
#define IDC_EYE_VIEW_NAME               1349
#define IDC_EYE_VIEW_LIST               1350
#define IDC_EYE_VIEW_RENAME             1351
#define IDC_EYE_VIEW_NEW                1352
#define IDC_MESSAGE                     1352
#define IDC_EYE_VIEW_GO_TO              1353
#define IDC_TRACK_PARENT                1353
#define IDC_EYE_VIEW_DELETE             1354
#define IDC_TRACK_VISIBLE               1354
#define IDC_TRACK_TRANSLATE             1355
#define IDC_TRACK_ROTATE                1356
#define IDC_TRACK_TRANSLATE_X           1357
#define IDC_TRACK_TRANSLATE_Y           1358
#define IDC_TRACK_TRANSLATE_Z           1359
#define IDC_TRACK_INCREASE_X            1360
#define IDC_TRACK_DECREASE_X            1361
#define IDC_TRACK_INCREASE_Y            1362
#define IDC_TRACK_DECREASE_Y            1363
#define IDC_TRACK_INCREASE_Z            1364
#define IDC_TRACK_DECREASE_Z            1365
#define IDC_TRACK_ROTATE_X              1366
#define IDC_TRACK_ROTATE_Y              1367
#define IDC_TRACK_ROTATE_Z              1368
#define IDC_TRACK_INCREASE_X90          1369
#define IDC_TRACK_RED                   1370
#define IDC_TRACK_INCREASE_Y90          1371
#define IDC_TRACK_INCREASE_Z90          1372
#define IDC_TRACK_RED_RESTORE           1373
#define IDC_TRACK_GREEN                 1374
#define IDC_TRACK_SNAP_TO               1375
#define IDC_TRACK_SLIDER_RED            1376
#define IDC_TRACK_SLIDER_GREEN          1377
#define IDC_TRACK_GREEN_RESTORE         1378
#define IDC_TRACK_BLUE                  1379
#define IDC_TRACK_SLIDER_BLUE           1380
#define IDC_TRACK_BLUE_RESTORE          1381
#define IDC_TRACK_TYPE                  1382
#define IDC_TRACK_START_X               1384
#define IDC_TRACK_START_Y               1385
#define IDC_STATIC_NUMBER               1386
#define IDC_TRACK_END_X                 1387
#define IDC_TRAIN_POSITION_X            1387
#define IDC_TRACK_END_Y                 1388
#define IDC_TRAIN_POSITION_Y            1388
#define IDC_STATIC_SWITCH               1389
#define IDC_TRAIN_VELOCITY              1389
#define IDC_TRACK_SWITCH_X              1390
#define IDC_TRAIN_ACCELERATION          1390
#define IDC_TRACK_SWITCH_Y              1391
#define IDC_TRAIN_TRACK                 1391
#define IDC_STATIC_RADIUS               1392
#define IDC_TRAIN_RELATIVE_POSITION     1392
#define IDC_TRACK_SWITCH_CLOSED         1393
#define IDC_TRAIN_GO                    1393
#define IDC_TRACK_SWITCH_OPENED         1394
#define IDC_TRACK_RADIUS                1395
#define IDC_STATIC_HEADING              1396
#define IDC_TRACK_HEADING               1397
#define IDC_STATIC_TRACK                1399
#define IDC_CONVEYOR_STOP               1402
#define IDC_CONVEYOR_SEGMENT_LIST       1403
#define IDC_CONVEYOR_MAX_SPEED          1404
#define IDC_CONVEYOR_REL_SPEED          1405
#define IDC_CONVEYOR_ACCEL              1406
#define IDC_CONVEYOR_STOP_GATE_LIST     1410
#define IDC_CONVEYOR_TRANS_LIFT_LIST    1411
#define IDC_CONVEYOR_REVERSE            1417
#define IDC_CONVEYOR_PAUSE              1418
#define IDC_BCR_GET_CODE                1418
#define IDC_CONVEYOR_FORWARD            1419
#define IDC_CONVEYOR_STOP_GATE_UP       1420
#define IDC_BCR_CODE                    1420
#define IDC_CONVEYOR_STOP_GATE_DOWN     1421
#define IDC_CONVEYOR_TRANS_LIFT_UP      1422
#define IDC_BCR_TRIGGER                 1422
#define IDC_CONVEYOR_TRANS_LIFT_DOWN    1423
#define IDC_BARRETTHAND_MIDDLE          1424
#define IDC_BARRETTHAND_TIP             1425
#define IDC_BARRETTHAND_JOINT_OPEN      1426
#define IDC_BARRETTHAND_JOINT_CLOSE     1427
#define IDC_SCALE_KG                    1428
#define IDC_SCALE_LB                    1429
#define IDC_SCALE_GET_MASS              1430
#define IDC_SCALE_MASS                  1431
#define IDC_SCRIPT_EDIT                 1432
#define IDC_SCRIPT_NEW                  1433
#define IDC_SCRIPT_OPEN                 1434
#define IDC_SCRIPT_SAVE                 1435
#define IDC_SCRIPT_SAVE_AS              1436
#define IDC_SCRIPT_PAUSE_PLAY           1437
#define IDC_SCRIPT_REWIND               1438
#define IDC_SCRIPT_LOOP                 1439
#define IDC_SCRIPT_PAUSE                1440
#define IDC_SCRIPT_LIST                 1441
#define IDC_MODE_SCRIPT                 1442
#define IDC_SCRIPT_PLAY                 1442
#define IDC_LIGHTING_SUN_ALTITUDE       1443
#define IDC_LIGHTING_SUN_AZIMUTH        1444
#define IDC_LIGHTING_SUN_VISIBLE        1445
#define IDC_LIGHTING_SUN_EYE            1446
#define IDC_GRID_RED_RESTORE            1447
#define IDC_LIGHTING_SUN_RIGHT          1447
#define IDC_GRID_GREEN_RESTORE          1448
#define IDC_LIGHTING_SUN_ALTITUDE_RESTORE 1448
#define IDC_GRID_BLUE_RESTORE           1449
#define IDC_LIGHTING_SUN_AZIMUTH_RESTORE 1449
#define IDC_CAMERA_ENABLED              1449
#define IDC_GRID_LENGTH_RESTORE         1450
#define IDC_LIGHTING_SUN_INTENSITY_RESTORE 1450
#define IDC_CAMERA_FIELD_OF_VIEW        1450
#define IDC_GRID_WIDTH_RESTORE          1451
#define IDC_LIGHTING_RED_RESTORE        1451
#define IDC_CAMERA_SLIDER_FIELD_OF_VIEW 1451
#define IDC_GRID_SPACING_RESTORE        1452
#define IDC_LIGHTING_ALPHA_RESTORE      1452
#define IDC_RESTORE_CAMERA_FIELD_OF_VIEW 1452
#define IDC_LIGHTING_GREEN_RESTORE      1453
#define IDC_RESTORE_CAMERA_CLIP_FRONT   1453
#define IDC_LIGHTING_BLUE_RESTORE       1454
#define IDC_CAMERA_CLIP_FRONT           1454
#define IDC_RESTORE_CAMERA_CLIP_REAR    1455
#define IDC_LIGHTING_SUN_LEFT           1455
#define IDC_CAMERA_CLIP_REAR            1456
#define IDC_WALK                        1458
#define IDC_LIGHTING_SUN_FRONT          1458
#define IDC_PAN                         1459
#define IDC_DEVICE_TRANSLATE            1460
#define IDC_EYE                         1461
#define IDC_SCRIPT                      1462
#define IDC_RECORD                      1463
#define IDC_SOCKET                      1464
#define IDC_EYE_ON                      1465
#define IDC_SCRIPT_ON                   1466
#define IDC_RECORD_ON                   1467
#define IDC_SOCKET_LISTEN               1468
#define IDC_WALK_ON                     1469
#define IDC_PAN_ON                      1470
#define IDC_DEVICE_TRANSLATE_ON         1471
#define IDC_LEFT_BACKGROUND             1472
#define IDC_SOCKET_CONNECT              1473
#define IDC_EYE_BACKGROUND              1473
#define IDC_PLAYBACK_BACKGROUND         1477
#define IDC_TOP_BACKGROUND              1478
#define IDC_SIZE_WIDTH                  1485
#define IDC_SIZE_HEIGHT                 1486
#define IDC_INVISIBLE                   1486
#define IDC_RADIO1                      1489
#define IDC_PART_ORIGIN_VISIBLE         1491
#define IDC_NETWORK_PORT                1492
#define IDC_LIGHTING_DEFAULTS           1493
#define IDC_GRID_DEFAULTS               1494
#define IDC_UNITS_DEFAULTS              1495
#define IDC_NETWORK_DEFAULTS            1496
#define IDC_RENDER_DEFAULTS             1497
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_PREFS                        32771
#define ID_VIEW_DEVICETREE              32773
#define ID_VIEW_DEVICE_TREE             32774
#define ID_MOTION_INSERT_HOLD           32775
#define ID_MOTION_INSERT_ANCHOR         32776
#define ID_MOTION_VIEW_HISTORY          32777
#define ID_VIEW_CURRENT_PART            32778
#define ID_DEVICE_CHOOSE                32779
#define ID_DEVICE_ATTACH                32780
#define ID_DEVICE_DETACH                32781
#define ID_DEVICE_CLONE                 32782
#define ID_DEVICE_RENAME                32783
#define ID_DEVICE_DELETE                32784
#define ID_SIZE_320X240                 32785
#define ID_SIZE_640X480                 32786
#define ID_MOTION_INSERT_PART_HOLD      32787
#define ID_MOTION_INSERT_PART_ANCHOR    32788
#define ID_MOTION_VIEW_PART_HISTORY     32789
#define ID_DEVICE_CREATE                32791
#define ID_PART_CHOOSE                  32792
#define ID_PART_UPDATE                  32793
#define ID_PART_ATTACH                  32794
#define ID_PART_DELETE                  32795
#define ID_PART_RENAME                  32796
#define ID_HELP_ANALYSIS                32798
#define ID_TAG_NEW_PATH                 32799
#define ID_TAG_CREATE                   32800
#define ID_TAG_TAG_ON_TCF               32801
#define ID_TAG_DELETE                   32802
#define ID_TAG_DELETE_PATH              32803
#define ID_TAG_REATTACH_PATH            32804
#define ID_TAG_RENAME_PATH              32805
#define ID_TAG_CHOOSE                   32806
#define ID_DEVICE_IMPORT                32808
#define ID_VIEW_EYE_INFO                32809
#define ID_VIEW_CURRENT_TAG             32810
#define ID_FILE_REVERT                  32814
#define ID_DEVICE_EXPORT                32817
#define ID_TAG_CHOOSE_PATH              32818
#define ID_SIZE_CUSTOM                  32819
#define ID_SIZE_720X480                 32820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        217
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1498
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
